### ISSUE TITLE
The access and publication of this software has been eliminated/banned from chrome app store.

### ISSUE THREAD

**Issue by wingsofdivine** [zacyu/bilibili-helper#142] opened 2016-04-05 03:28 UTC
as title, can't install even if you make a hard copy of it and install it on another computer, the chrome does not recognize this extension as a safe app and as a working .crx

also as a user of this app I appreciate your hard work but if the app is removed from chrome you really should put the original app/extension on here or on your personal website.

**Comment by zacyu** [comment] 2016-04-05 03:41
Thanks for your feedback. I submitted the version 0.8.4 of this extension to Google Chrome Webstore a few days ago, and it's still pending review. I am trying my best to have this resolved as soon as possible, but as for now, I have received a clear response regarding when they will finish their review or when the extension will be available for publication or installation again.
Meanwhile, although not recommended, you can clone the source code of this extension and load it to your browser with the "load unpacked extension" button under "developer mode." manually. Note that if you actually do it that way, you would have it update it manually (with `git pull`) as well.
Hopefully this process won't take anything longer than 7 to 10 days (according to them), but I will keep you updated. Thanks again for your support and understanding. I apologize for any inconvenience caused by this incident.

**Comment by zacyu** [comment] 2016-04-05 03:43
Also, this is a duplicate of #140, all further discussion should go to that issue instead. Thanks.

**Closed by zacyu** 2016-04-05 03:43 UTC
Labels: duplicate
