### ISSUE TITLE
与Unblock Youku冲突

### ISSUE THREAD

**Issue by eddiey233** [zacyu/bilibili-helper#72] opened 2015-10-30 22:54 UTC
RT
Chrome 版本 46.0.2490.80 m

![01](https://cloud.githubusercontent.com/assets/15482474/10859796/38f23ea8-7f1e-11e5-8415-5876eafe79b8.png)

**Comment by zacyu** [comment] 2015-10-31 06:31
Duplicate of #63

**Closed by zacyu** 2015-10-31 06:31 UTC
